This is a program to predict the games selected by users based on the queries searched by him. The dataset we have used is from besy buy and contains data for XBOX games.

In [1]:
#importing libraries
import numpy as np
import pandas as pd
train = pd.read_csv('all/train.csv')
test = pd.read_csv('all/test.csv')

In [2]:
#Split the data into training and testing to check the accuracy
from sklearn.model_selection import train_test_split

In [3]:
X = train[['user','category','query','click_time','query_time']]
y = train['sku']

In [4]:
X[0:10]

user      category           query  \
0  0001cd0d10bbc585c9ba287c963e00873d4c0bfd  abcat0701002    gears of war   
1  00033dbced6acd3626c4b56ff5c55b8d69911681  abcat0701002    Gears of war   
2  00033dbced6acd3626c4b56ff5c55b8d69911681  abcat0701002    Gears of war   
3  00033dbced6acd3626c4b56ff5c55b8d69911681  abcat0701002  Assassin creed   
4  0007756f015345450f7be1df33695421466b7ce4  abcat0701002     dead island   
5  000878e35cb70ace315dbdbef54c22477066f07e  abcat0701002       Rocksmith   
6  0008b7e06bc3d329b4dc052268e10b98c9121452  abcat0701002         Nba n2k   
7  0008f35cccf771838c635196205951403f13da50  abcat0701002    Call of duty   
8  000c22a204a9248e3e5458ed52a084b98ddfcf56  abcat0701002       rock band   
9  000f573f22d30ead7a0a3d7fce64d3eb1cb8d0be  abcat0701002            xbox   

                click_time               query_time  
0  2011-10-09 17:22:56.101  2011-10-09 17:21:42.917  
1  2011-09-25 13:35:42.198  2011-09-25 13:35:33.234  
2  2011-09-25 13:36:08.668  2011-09-25 13:35:33.234  
3  2011-09-25 13:37:23.709  2011-09-25 13:37:00.049  
4  2011-09-11 15:15:34.336  2011-09-11 15:15:26.206  
5  2011-10-25 20:44:36.756  2011-10-25 20:44:22.861  
6  2011-10-29 20:10:06.459  2011-10-29 20:09:33.475  
7  2011-08-12 18:05:40.887  2011-08-12 18:05:06.414  
8  2011-10-07 00:02:54.236  2011-10-07 00:02:44.212  
9  2011-09-30 08:39:51.651  2011-09-30 08:36:40.246

In [5]:
#Vectorize the data to perform modelling
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()

In [6]:
query_vec = vectorizer.fit_transform(X['query'])

In [7]:
X_train, X_test, y_train, y_test = train_test_split(query_vec, y, test_size=0.33, random_state=101)

In [8]:
import matplotlib.pyplot as plt
import numpy as np
%matplotlib inline
from sklearn import svm, metrics, datasets
from sklearn.model_selection import GridSearchCV, train_test_split

In [9]:
#Finding the best parameters for Grid Searc

param_grid = [ {'C': [1, 10, 100, 1000], 'kernel': ['linear']},
  {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']},]

#Create SVM model and fit the training data
svc = svm.SVC()
clf = GridSearchCV(svc, param_grid, refit = True, verbose = 3)
clf.fit(X_train, y_train)

Fitting 3 folds for each of 12 candidates, totalling 36 fits
[CV] C=1, kernel=linear ..............................................


C:\Users\kashi\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


[CV] ..... C=1, kernel=linear, score=0.6216834876703777, total= 1.2min
[CV] C=1, kernel=linear ..............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:  3.0min remaining:    0.0s


[CV] ..... C=1, kernel=linear, score=0.6263620014810113, total= 1.1min
[CV] C=1, kernel=linear ..............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed:  6.3min remaining:    0.0s


[CV] ...... C=1, kernel=linear, score=0.634549356223176, total= 1.2min
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6199146810945791, total=  55.1s
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6275256532317782, total= 1.1min
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6305793991416309, total= 1.1min
[CV] C=100, kernel=linear ............................................
[CV] ... C=100, kernel=linear, score=0.6164811153886172, total= 1.2min
[CV] C=100, kernel=linear ............................................
[CV] ... C=100, kernel=linear, score=0.6245636305934624, total= 2.7min
[CV] C=100, kernel=linear ............................................
[CV] ... C=100, kernel=linear, score=0.6282188841201717, total= 2.3min
[CV] C=1000, kernel=linear ...........................................
[CV] .

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed: 252.6min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [10]:
#Predict the SKUs for the training dta
pred = clf.predict(X_test)

In [11]:
#Evaluate the model using Confustion matrix
print("Confusion Matrix for - \n{}:\n{}\n".format(clf, metrics.confusion_matrix(y_test, pred)))

Confusion Matrix for - 
GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3):
[[15  0  0 ...  0  0  0]
 [ 0  4  0 ...  0  0  0]
 [ 1  0  0 ...  0  0  0]
 ...
 [ 0  0  0 ...  0  0  0]
 [ 0  0  0 ...  0 12  0]
 [ 0  0  0 ...  0  0  0]]



In [12]:
#SKU predictions
pred

array([8887644, 2541184, 9854804, ..., 3552327, 9854804, 2945052],
      dtype=int64)

In [13]:
#Evaluate the model using Classification report to check Precision, recall and F1-score
print("Classification Report for - \n{}:\n{}\n".format(
    clf, metrics.classification_report(y_test, pred)))

Classification Report for - 
GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3):
                  precision    recall  f1-score   support

         1004622       0.68      0.83      0.75        18
         1010544       1.00      1.00      1.00         4
         1011067       0.00      0.00      0.00         1
         1011491       1.00      0.35      0.52        23
         1011831       0.00      0.00      0.00         3
         1012721       0.84      0.89      0.86

C:\Users\kashi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1135: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)
C:\Users\kashi\Anaconda3\lib\site-packages\sklearn\metrics\classification.py:1137: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples.
  'recall', 'true', average, warn_for)


In [14]:
#Apply the same technique for the entire dataset

X_final = train[['query','user']]
y_final = train['sku']
query_vec1 =  vectorizer.fit_transform(X_final['query'])

In [15]:
test = pd.read_csv('all/test.csv')
test[0:10]
X_final_test = test[['query','user']]

In [16]:
query_vec2 =  vectorizer.fit_transform(X_final_test['query'])

In [17]:
#Fit the entire training data
clf.fit(query_vec1,y_final)

Fitting 3 folds for each of 12 candidates, totalling 36 fits


C:\Users\kashi\Anaconda3\lib\site-packages\sklearn\model_selection\_split.py:605: Warning: The least populated class in y has only 1 members, which is too few. The minimum number of members in any class cannot be less than n_splits=3.
  % (min_groups, self.n_splits)), Warning)


[CV] C=1, kernel=linear ..............................................
[CV] ..... C=1, kernel=linear, score=0.6303586438778369, total= 5.2min
[CV] C=1, kernel=linear ..............................................


[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed: 11.1min remaining:    0.0s


[CV] ..... C=1, kernel=linear, score=0.6356424422722765, total= 2.2min
[CV] C=1, kernel=linear ..............................................


[Parallel(n_jobs=1)]: Done   2 out of   2 | elapsed: 17.4min remaining:    0.0s


[CV] ..... C=1, kernel=linear, score=0.6378927778970725, total= 2.4min
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6281171196413561, total= 2.1min
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6344383057090239, total= 2.2min
[CV] C=10, kernel=linear .............................................
[CV] .... C=10, kernel=linear, score=0.6367475484933076, total= 2.2min
[CV] C=100, kernel=linear ............................................
[CV] .... C=100, kernel=linear, score=0.625245166713365, total= 2.1min
[CV] C=100, kernel=linear ............................................
[CV] ... C=100, kernel=linear, score=0.6318175378948859, total= 2.3min
[CV] C=100, kernel=linear ............................................
[CV] ... C=100, kernel=linear, score=0.6340992054971012, total= 2.3min
[CV] C=1000, kernel=linear ...........................................
[CV] .

[Parallel(n_jobs=1)]: Done  36 out of  36 | elapsed: 266.5min finished


GridSearchCV(cv=None, error_score='raise',
       estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
  decision_function_shape='ovr', degree=3, gamma='auto', kernel='rbf',
  max_iter=-1, probability=False, random_state=None, shrinking=True,
  tol=0.001, verbose=False),
       fit_params=None, iid=True, n_jobs=1,
       param_grid=[{'C': [1, 10, 100, 1000], 'kernel': ['linear']}, {'C': [1, 10, 100, 1000], 'gamma': [0.001, 0.0001], 'kernel': ['rbf']}],
       pre_dispatch='2*n_jobs', refit=True, return_train_score='warn',
       scoring=None, verbose=3)

In [21]:
#Predict the outcone for Test data
final_pred =  clf.predict(query_vec2)

In [24]:
final_pred[0:50]

array([9865018, 1161734, 2704058, 2375195, 9739989, 1078792, 2670133,
       9854804, 2670133, 9854804, 9276473, 2704058, 2078113, 2945052,
       9854804, 2670133, 2107458, 2897116, 2107458, 2945052, 9854804,
       2078113, 2173065, 2107458, 1092494, 2712876, 2107458, 2173065,
       9691527, 2670133, 2802508, 9854804, 9955514, 2173065, 2670133,
       2633103, 1067848, 2807036, 2541184, 2173065, 1563461, 9854804,
       2541184, 9902347, 2375195, 2953607, 9854804, 2977637, 9854804,
       9854804], dtype=int64)